[listener]
type="socket"

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[[port]]
ports=["tcp/8022"]
services=["ssh-simulator"]

[service.telnet]
type="telnet"
prompt=">"

[[port]]
port="tcp/8023"
services=["telnet"]

#-----------------------

[service.ftp]
type="ftp"

[[port]]
port="tcp/8021"
services=["ftp"]

#-----------------------

[service.http01]
type="http"
server="Nginx"

[[port]]
port="tcp/8080"
services=["http01"]

#-----------------------

[service.redis]
type="redis"
version="4.0.2"
os="Linux 2.6.32-431.el6.x86_64 x86_64"

[[port]]
port="tcp/6379"
services=["redis"]


[channel.console]
type="console"

[[filter]]
channel=["console"]
